spring:
  application:
    name: SpringAI-chat-memory

  ai:
    openai:
      api-key:
      chat:
        memory:
          repository:
            jdbc:
              initialize-schema: NEVER

    vectorstore:
        qdrant:
          initialize-schema: true
          host: localhost
          port: 6334
          collection-name: java


  docker:
    compose:
      stop:
        command: DOWN

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: yell
    password: yell123

    sql:
      init:
        mode: always

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG

server:
  port: 9292
